version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - export NODE_OPTIONS="--max-old-space-size=8192"
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build

  # xyzhospital-backend-dev-serverlessdeploymentbucke-qhylix3wc4d2