name: Deployment
on:
  push:
    branches: [ master ]

env:
  VITE_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  VITE_APP_IMG_URL: ${{ secrets.REACT_APP_IMG_URL }}
  VITE_APP_USER_POOL_ID: ${{ secrets.REACT_APP_USER_POOL_ID }}
  VITE_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
  VITE_APP_REGION: ${{ secrets.REACT_APP_REGION }}

jobs:
  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV
      - name: installing node 
        uses: actions/setup-node@v2
        with: 
          node-version: '20'
      - name: Install dependencies
        run: pnpm ci
      - name: creating build
        run: pnpm run build
        
      - name: Deploy to srurge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'xyzhospital.surge.sh'
          project: './build'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

