name: Deployment
on: push

# on:
#   push:
#     branches: [ main ]
jobs:
  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      # - name: installing node 
      #   uses: actions/setup-node@v2
      #   with: 
      #     node-version: '14'
      # - name: Install dependencies
      #     run: npm ci
      - name: creating build
        run: npm run build
        
      - name: Deploy to srurge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'xyzhospital.surge.sh'
          project: './build'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

