name: Shell Commands

on:
  repository_dispatch:
    types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
