name: Node.js CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  NODE_ENV: dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set the env variable value
        id: step_one
        run: |
          echo "NODE_ENV=dev" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm ci
      - run : npm run lint